### ISSUE TITLE
Findings upload has Python error

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#252]
Publishing findings fails with a Python error:

    Prepare findings of Tikanga in ex1 for upload to http://mubench.svamann.de/fse18-ext/...
    Preparing findings in project 'chensun' version cf23b99...
    Found 1 potential hits.
    Publishing potential hits...
    'Finding' object has no attribute 'files'

The full trace is

    Traceback (most recent call last):
    File "/mubench/mubench.pipeline/tasks/task_runner.py", line 35, in __run
      results = task.run(*parameter_values)
    File "/mubench/mubench.pipeline/tasks/implementations/publish_findings.py", line 60, in run
      for potential_hits_slice in self.__slice_by_max_files_per_post(potential_hits.findings):
    File "/mubench/mubench.pipeline/tasks/implementations/publish_findings.py", line 81, in __slice_by_max_files_per_post
      number_of_files_in_hit = len(potential_hit.files)

**Comment by salsolatragus** [comment]
The `PublishFindingsTask` confused findings and specialized findings, which resulted in the above error. I cleaned up the retrieval, specialization, and post-preparation of findings in the task, to fix the problem and to help avoid respective confusions in the future.
