### ISSUE TITLE
Export of CSV fails with Exception

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#83]
Attempting to download any CSV from the review site currently fails with the following exception:

```
[2017-08-16 09:54:16] mubench.CRITICAL: exception 'InvalidArgumentException' with message 'Slim\Http\Stream::attach argument must be a valid PHP resource' in /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/slim/slim/Slim/Http/Stream.php:149
Stack trace:
#0 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/slim/slim/Slim/Http/Stream.php(98): Slim\Http\Stream->attach(false)
#1 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/src/Controller/DownloadController.php(57): Slim\Http\Stream->__construct(false)
#2 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/src/Controller/DownloadController.php(51): MuBench\ReviewSite\Controller\DownloadController->download(Object(Slim\Http\Response), 'sep=,\nproject,v...', 'MuDetect.csv')
#3 [internal function]: MuBench\ReviewSite\Controller\DownloadController->download_run_stats(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/slim/slim/Slim/Route.php(325): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/slim/slim/Slim/Route.php(297): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/slim/slim/Slim/App.php(443): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/tuupola/slim-basic-auth/src/HttpBasicAuthentication.php(87): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 [internal function]: Slim\Middleware\HttpBasicAuthentication->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#11 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Slim\Middleware\HttpBasicAuthentication), Array)
#12 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#13 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#14 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/slim/slim/Slim/App.php(337): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/vendor/slim/slim/Slim/App.php(298): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/index.php(20): Slim\App->run()
#18 {main} [] {"uid":"8f06284"}
```

**Comment by salsolatragus** [comment]
We found that

```
2, fopen(): data:// wrapper is disabled in the server configuration by allow_url_fopen=0, /kunden/427951_61118/webseiten/www.st.informatik.tu-darmstadt.de/artifacts/mubench/reviews/icse18/src/Controller/DownloadController.php, 60
```

is the source of the problem. Unfortunately, we cannot change this setting on the server. Is there another way to do this?
